/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 scene.gltf --transform
Author: hexabear2020 (https://sketchfab.com/hexabear2020)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hexaberry-soda-cans-96aa6a20264848ab9c5be2478594ec44
Title: HexaBerry Soda Cans
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";

const firstVariant = {
  visible: { opacity: 1, transition: { duration: 2 }, y:0, rotateX:-Math.PI / 3,   rotateY:-11.95, rotateZ:-1.489 },
  hidden: { opacity: 0, y:150, rotateY:-11.95, rotateZ:-1.489, rotateX:-Math.PI / 1, }
};

const secondVariant = {
  visible: { opacity: 1, transition: { duration: 1 }, y:0  },
  hidden: { opacity: 0, y:-150 }
};
export function Model(props) {
  const { nodes, materials } = useGLTF("/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <motion.group initial='hidden' variants={firstVariant}animate='visible' position={[-25, 5, -27.255]} rotation={[-Math.PI / 3, -11.95, -1.489]}>
        <mesh geometry={nodes.Soda_2_Soda001_0.geometry} material={materials["Soda.003"]} scale={9.104} />
        <mesh geometry={nodes.Soda_2_Metal001_0.geometry} material={materials["Metal.001"]} scale={9.104} />
      </motion.group>

      <motion.group initial='hidden' animate='visible' variants={secondVariant} position={[30, 5, -50.255]} rotation={[-Math.PI / 2, 6.1, -1.547]}>
        <mesh geometry={nodes.Soda_3_Soda002_0.geometry} material={materials["Soda.002"]} scale={9.104} />
        <mesh geometry={nodes.Soda_2_Metal001_0.geometry} material={materials["Metal.002"]} scale={9.104} />
      </motion.group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
